### ISSUE TITLE
Initial setup of Electron JS with React/Redux

### ISSUE THREAD

**Issue by ViniciusBernardo** [PI2-Analisador-de-tubulacao/olhaduto-app#1]
#### _**Tasks**_

- [x]  Study Electron JS documentation

- [x] Search how to integrate with React and Redux

#### **Critérios de Aceitação**

- [x]  At least home window using React with Electron App

**Pontos:** 1
**Prioridade:** MUST 

**Responsáveis:** Vinícius

**Comment by ViniciusBernardo** [comment]
While I studied about Electron JS, I found at the official documentation a boilerplate with the template of an Electron + React application.

[electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)
