### ISSUE TITLE
[Feature] Controlar o movimento da câmera

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#10]
**RF02** - Controlar o movimento da câmera

#### _**Tasks**_

- [ ] Conectar o robô

- [ ] Movimentar câmera

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] A câmera deve se movimentar
- [ ] Deve existir um atalho no teclado
