### ISSUE TITLE
[Feature] Controlar intensidade da iluminação

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#11]
**RF03** - Controlar intensidade da iluminação

#### _**Tasks**_

- [x] Conectar o robô

- [ ] Controlar intensidade da iluminação

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] A iluminação da plataforma deve ser manipulada
- [ ] Deve existir um atalho no teclado
