### ISSUE TITLE
[Feature] Visualizar transmissão da câmera

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#12]
**RF05** - Visualizar transmissão da câmera

#### _**Tasks**_

- [ ] Conectar o robô

- [ ] Conectar com a câmera

- [ ] Apresentação no Front

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] Visualizar transmissão da câmera
- [ ] Deve existir um atalho no teclado
