### ISSUE TITLE
[Feature] Armazenar o vídeo

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#13]
**RF06** - Armazenar o vídeo

#### _**Tasks**_

- [ ] Gravar vídeo

- [ ] Armazenar vídeo

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] A plataforma deve gravar
- [ ] Guardar gravação
- [ ] Deve existir um atalho no teclado
