### ISSUE TITLE
[Feature] Adicionar frame atual ao relatório

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#14]
**RF07** - Adicionar frame atual ao relatório

#### _**Tasks**_

- [ ] Identificar frame
- [ ] Guardar imagem
- [ ] Adicionar ao relatório
- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] No relatório deve conter frame selecionado
- [ ] Deve existir um atalho no teclado
