### ISSUE TITLE
[Feature] Adicionar comentário ao frame atual

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#17]
**RF010** - Adicionar comentário ao frame atual

#### _**Tasks**_

- [ ] Criar comentário

- [ ] Associar comentário ao frame

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] Adicionar comentário ao frame atual
- [ ] Deve existir um atalho no teclado
