### ISSUE TITLE
[Feature] Usuário validar resultado da predição do modelo

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#25]
**RF020** - Usuário validar resultado da predição do modelo

#### _**Tasks**_

- [ ] Apresentar resultado para usuário

- [ ] Gravar resultado da análise do usuário

#### **Critérios de Aceitação**

- [ ] Usuário validar resultado da predição do modelo
