### ISSUE TITLE
[Feature] Desabilitar aprendizado contínuo automaticamente para computadores com limitação de recurso

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#28]
**RF023** - Desabilitar aprendizado contínuo automaticamente para computadores com limitação de recurso

#### _**Tasks**_

- [ ] Desabilitar aprendizado contínuo

- [ ] Colocar opção nas configurações 

#### **Critérios de Aceitação**

- [ ] Desabilitar aprendizado contínuo
