### ISSUE TITLE
[Feature] Relatório mantém registro das patologias e sua respectiva localização encontradas na inspeção

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#34]
**RF032** - Relatório mantém registro das patologias e sua respectiva localização encontradas na inspeção

#### _**Tasks**_

- [ ] Manter registro da patologia

- [ ] Manter registro da localização

#### **Critérios de Aceitação**

- [ ] Manter registro das patologias e sua respectiva localização encontradas na inspeção
