### ISSUE TITLE
[Feature] Teste

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#45]
**RF01** - Controlar o deslocamento do robô

#### _**Tasks**_

- [ ] Conectar o robô

- [ ] Movimentar plataforma

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] A plataforma deve se movimentar
- [ ] Deve existir um atalho no teclado

**Pontos:** 5
**Prioridade:** MUST

**Responsáveis:** Vinícius
