### ISSUE TITLE
[Feature] Implementar tela de controle

### ISSUE THREAD

**Issue by ViniciusBernardo** [PI2-Analisador-de-tubulacao/olhaduto-app#46]
#### _**Tasks**_

- [x] Implementar componente para página de controle

- [x] Adicionar link para o componente no relatório

#### **Critérios de Aceitação**

- [x] Seguir o padrão do figma
- [x] Deve existir uma rota para página

**Pontos:** 3
**Prioridade:** MUST

**Responsáveis:** Vinícius
