### ISSUE TITLE
[Feature] Adicionar estrutura de páginas na aplicação

### ISSUE THREAD

**Issue by ViniciusBernardo** [PI2-Analisador-de-tubulacao/olhaduto-app#47]
**RF01** - Controlar o deslocamento do robô

#### _**Tasks**_

- [x] Adicionar o componente de cada página de aplicação

- [x] Criar uma pasta que contenha apenas esses componentes

#### **Critérios de Aceitação**

- [x] Componentes escritos em TypeScript

**Pontos:** 1
**Prioridade:** MUST

**Responsáveis:** Vinícius
