### ISSUE TITLE
[Feature] Integrar libs do ROS no javascript

### ISSUE THREAD

**Issue by icaropires** [PI2-Analisador-de-tubulacao/olhaduto-app#58]
#### _**Tasks**_

- [ ] Integrar [roslibjs](https://github.com/RobotWebTools/roslibjs)
- [ ] Integrar [ros2-web-bridge](https://github.com/RobotWebTools/ros2-web-bridge)
- [ ] Dockerizar

#### **Critérios de Aceitação**

- [ ] Libs instaladas
- [ ] Servidor da bridge executando ao mesmo tempo que o restante da aplicação
