### ISSUE TITLE
[Feature] Controlar o deslocamento do robô

### ISSUE THREAD

**Issue by AnaCarolcs** [PI2-Analisador-de-tubulacao/olhaduto-app#9]
**RF01** - Controlar o deslocamento do robô

#### _**Tasks**_

- [x] Conectar o robô

- [ ] Movimentar plataforma

- [ ] Atalho de controle

#### **Critérios de Aceitação**

- [ ] A plataforma deve se movimentar
- [ ] Deve existir um atalho no teclado
